# Generated by Django 3.0.4 on 2020-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('emailid', models.CharField(max_length=40, unique=True)),
                ('rollno', models.CharField(max_length=4, unique=True)),
                ('team', models.CharField(max_length=1)),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
